defaults: &defaults
  docker:
    - image: circleci/node:14

version: 2
jobs:
  pre-build:
    working_directory: ~/defensive-stance
    <<: *defaults
    steps:
      - checkout:
          path: ~/defensive-stance/
      - attach_workspace:
          at: ~/defensive-stance/

      - restore_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v2-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/defensive-stance
          paths:
            - node_modules
  lint:
    working_directory: ~/defensive-stance
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/defensive-stance
      - run: npm run lint

  gatsby-deploy:
    working_directory: ~/defensive-stance
    <<: *defaults
    steps:
      - checkout:
          path: ~/defensive-stance/
      - attach_workspace:
          at: ~/defensive-stance
      - run:
          command: |
            sudo apt-get -y -qq install awscli
            CI=false npm run build:ci
            aws s3 sync public/ s3://defensive-stance-prod  --region us-east-1 --delete
workflows:
  version: 2
  front-backend:
    jobs:
      - pre-build:
          filters:
            branches:
              only:
                - main
      - lint:
          requires:
            - pre-build
      - gatsby-deploy:
          requires:
            - lint
          filters:
            branches:
              only:
                - main